[package]
name = "calling-lindera"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
lindera = "0.7.1"
lindera-core = "0.7.1"
wasm-bindgen = "0.2"
serde_json = "*"